import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import Header from "@/components/Header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  authors: [
    {
      name: "Thiti Tongumpun",
      url: "https://github.com/thititongumpun",
    },
  ],
  icons: [
    { rel: "apple-touch-icon", url: "icons/icon-128x128.png" },
    { rel: "icon", url: "icons/icon-128x128.png" },
  ],
};

const fontSans = FontSans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen bg-background antialiased ${fontSans.className}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
